language: rust
cache: cargo
rust:
- stable
script:
- cargo build --verbose --all
- cargo test --verbose --all
notifications:
  email: false
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: vz3vMglhc9QnwmfhQKDTwFunVYRqKuRZFxO+D7wtdraVd+fESuWNa3MQrfTsH4JeUz4YjnF5VW4juf/PAx07ktlIp303u1kv3B854XgQ9/vGySNVoXvXiMMc1dZO6/8XA77amSdCZYJpMDdLCZlGgUXYshnQAV1hR3q07i5s6sYoFqq8C1CtBcPCIrjpCJl6PScWbBg+Y8iUO7Jl+O+CK0xynhnvZyMGGWL/FQ8Mf/DT/r75Rfl5KMGHmKSzq/UwDquR9ho+5O7tS80GAweBAVh9O47HRTmrkzC+3WcYh+EOsj2UTAt/eeiy6GVkzWliFlrOzYbOEbqADeVUKDUiwx8oBHPE9dawvV0mZlKKMfnNlOZ7rnbiAdXeaB/12tuBjoeFUfvuNCA1wPNTXJ/iYo/LJbXaN1pYGi4oU4fTt6bCPt6p+Bl5am4ETmlaL7uS/yWWM+2wL5jOjz57G7nUYtSYRDjGbMLUW18I6579hvCj+H9cCqjs53pB1ha9oAOMkqC/DlbvG6XUO5H+i8LIZUBB4nupF47UypzrwSOTfFzqk/JtmArHjph1hQAvYieXASiVPLB0Gqk/TatTGETaV6uhdsiqw09PRfknGGEMfjam9w414Mn+DAYI9UOTln0MyqUOJRUnl9IXoiMIOXHTERFFW5ZVQMuaLDL9mBrs6Ic=
